name: Build

on:
  push:
  pull_request:
    types:
      - opened
      - edited
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201

    - name: InitNuget
      env:
        SNAPSHOT_NUGET_PUBLISH_URL: github
        SNAPSHOT_NUGET_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      run: |
        dotnet nuget add source --username eventuateio \
          --password "$SNAPSHOT_NUGET_API_KEY" \
          --store-password-in-clear-text \
          --name github "https://nuget.pkg.github.com/eventuate-tram/index.json"

    - name: Build
      run: ./test.sh
